package enums;

public enum Action {
	MOVE,REGISTER,ACCESS,CUSREGISTER,CUSACCESS,CUST_LIST,CUST_RETRIEVE,DETAIL_UPDATE, CUST_FILE_UPLOAD, CUST_DELETE, PRODUCT_LIST, PRODUCT_UPDATE, PRODUCT_DELETE, PRODUCT_REGISTER, PRODUCT_RETRIEVE, CATEGORY_LIST
}
